INSERT INTO LOCATIONS (DESCRIPTION, LATITUDE, LONGITUDE)
VALUES ("Dodge Hall", -83.21655, 42.67186), ("MSC Floor 2 East", -83.21656, 42.67129), ("MSC Floor 1 East", -83.21655, 42.67134), ("MSC Floor 1 West", -83.21799, 42.67095), ("Hannah Hall", -83.21776, 42.67186), ("OC Floor 2", -83.21689, 42.67407), ("OC Floor 1 Near Bear Cave", -83.21690, 42.67389), ("OC Floor 1 Near Bookstore", -83.21628, 42.67473), ("O'Dowd Hall", -83.21521, 42.67451), ("Human Health Building Floor 4", -83.21963, 42.67759), ("Human Health Building Floor 4", -83.21963, 42.67759);

INSERT INTO MACHINES (LOCATIONID, SPECIFICLOCATION)
VALUES (1, "Machine closest to railing."), (2, "Machine closest to wall."), (3, "Machine closest to Dodge Hall."), (4, "Machine closest to wall."), (5, "Machine closest to railing."), (6, "Machine closest to door."), (7, "Machine closest to Habitat."), (8, "Machine closest to bathrooms."), (9, "Middle machine."), (10, "Machine closest to microwave.");

INSERT INTO ITEMS (NAME, DESCRIPTION)
VALUES ("Cheezits", "Cheesy snack crackers."), ("Veggie Straws", "Healthy-ish vegetable based potato chip alternative."), ("Funyuns", ""), ("Snyder's Pretzels", ""), ("Nacho Cheese Doritos", ""), ("Lays Potato Chips", ""), ("Cheetos", ""), ("Sour Cream And Cheddar Ruffles", ""), ("Baked Lays Potato Chips", ""), ("Cheese Pizza Combos", ""), ("Flamin Hot Limon Doritos", ""), ("Flamin Hot Cheetos", ""), ("Munchies", ""), ("Reese's Peanut Butter Cups", ""), ("KitKat", ""), ("Snickers", ""), ("Twix", ""), ("M&Ms", ""), ("Nature Valley Granola Bar", ""), ("Kind Bar", ""), ("Mint Orbit Gum", ""), ("Peanut M&Ms", ""), ("Teryaki Beef Jerky", ""), ("Classic Pringles", ""), ("Honey Bun", ""), ("Chips Ahoy", ""), ("Smores Pop Tart", ""), ("Cherry Poptart", ""), ("Rice Crispy Treat", ""), ("Jays Jalapeno Crunches", ""), ("Lays BBQ Chips", ""), ("Lays Baked BBQ Chips", ""), ("Lays Salt and Vinegar Chips", ""), ("Lays Dill Pickle Chips", ""), ("BBQ Fritos Twists", ""), ("Chilli Cheese Fritos", ""), ("Wintergreen Orbit Gum", ""), ("Cinnamon Toast Crunch", ""), ("Fruit Snacks", ""), ("Skittles", ""), ("Mini Starbursts", ""), ("Big Texas Cinnimon Bun", ""), ("Lays Baked Sour Cream and Onion Chips", ""), ("Good Natured Thins", ""), ("Lays Sour Cream and Onion Chips", ""), ("Pop Chips Bold Cheddar", ""), ("Chex Mix", ""), ("Jalepeno Cheddar Cheetos", ""), ("Elfin Crackers", ""), ("Gummy Bears", ""), ("Peanut Butter Cheddar Cracker Sandwiches", ""), ("3 Musketeers", ""), ("Flamin Hot Nacho Doritos", ""), ("Pork Rinds", ""), ("Pop Corners", ""), ("Payday", ""), ("Trail Mix", ""), ("NutriGrain Bar", ""), ("Hostess Glazed Donuts", ""), ("TGI Fridays Potato Skins", ""), ("Famous Amous Cookies", ""), ("White Cheddar Smartfood Popcorn", "");

INSERT INTO STOCKED_ITEMS (MACHINEID, ITEMID, TIMESTAMP, CERTAINTY, TAG)
VALUES (1, 31, NOW(), 0, ""), (1, 60, NOW(), 0, ""), (1, 11, NOW(), 0, ""), (1, 4, NOW(), 0, ""), (1, 5, NOW(), 0, ""), (1, 3, NOW(), 0, ""), (1, 7, NOW(), 0, ""),
 (2, 62, NOW(), 0, ""), (2, 5, NOW(), 0, ""), (2, 11, NOW(), 0, ""), (2, 4, NOW(), 0, ""), (2, 6, NOW(), 0, ""), (2, 31, NOW(), 0, ""), (2, 8, NOW(), 0, ""),
 (3, 1, NOW(), 0, ""), (3, 5, NOW(), 0, ""), (3, 8, NOW(), 0, ""), (3, 45, NOW(), 0, ""), (3, 56, NOW(), 0, ""), (3, 40, NOW(), 0, ""), (3, 28, NOW(), 0, ""),
 (4, 1, NOW(), 0, ""), (4, 31, NOW(), 0, ""), (4, 17, NOW(), 0, ""), (4, 3, NOW(), 0, ""), (4, 29, NOW(), 0, ""), (4, 37, NOW(), 0, ""), (4, 14, NOW(), 0, ""),
 (5, 15, NOW(), 0, ""), (5, 57, NOW(), 0, ""), (5, 49, NOW(), 0, ""), (5, 10, NOW(), 0, ""), (5, 7, NOW(), 0, ""), (5, 37, NOW(), 0, ""), (5, 1, NOW(), 0, ""),
 (6, 1, NOW(), 0, ""), (6, 54, NOW(), 0, ""), (6, 56, NOW(), 0, ""), (6, 23, NOW(), 0, ""), (6, 29, NOW(), 0, ""), (6, 14, NOW(), 0, ""), (6, 17, NOW(), 0, ""),
 (7, 30, NOW(), 0, ""), (7, 1, NOW(), 0, ""), (7, 20, NOW(), 0, ""), (7, 22, NOW(), 0, ""), (7, 43, NOW(), 0, ""), (7, 24, NOW(), 0, ""), (7, 16, NOW(), 0, ""), 
 (8, 1, NOW(), 0, ""), (8, 22, NOW(), 0, ""), (8, 51, NOW(), 0, ""), (8, 59, NOW(), 0, ""), (8, 50, NOW(), 0, ""), (8, 48, NOW(), 0, ""), (8, 13, NOW(), 0, ""), 
 (9, 1, NOW(), 0, ""), (9, 41, NOW(), 0, ""), (9, 40, NOW(), 0, ""), (9, 53, NOW(), 0, ""), (9, 46, NOW(), 0, ""), (9, 37, NOW(), 0, ""), (9, 3, NOW(), 0, ""),
 (10, 1, NOW(), 0, ""), (10, 5, NOW(), 0, ""), (10, 19, NOW(), 0, ""), (10, 16, NOW(), 0, ""), (10, 23, NOW(), 0, ""), (10, 15, NOW(), 0, ""), (10, 21, NOW(), 0, "");